### ISSUE TITLE
Local development setup

### ISSUE THREAD

**Issue by alisamar** [rayriffy/urami#18]
How do I integrate this into my local development setup? I couldn't find any documentation or examples on this. Do I have to specify a value like localhost:3000 for the domain? 

Thank you.

**Comment by rayriffy** [comment]
By default, the image component will be pointed to it's origin. ([being described here](https://urami.dev/components/overview#overview)).

But if you want to change it's default behavior and point to somewhere else, you can [create your own loader](https://urami.dev/utilities/loader) function to change resolve url to your target server.

**Comment by rayriffy** [comment]
Hello, how's it going? Is you issue resolved?

**Comment by alisamar** [comment]
Hey Riffy! Thanks a bunch for checking in. I haven't had a moment to test it out yet, but I'm planning to give it a go in my local environment this weekend. 😊 I'll keep you updated on the progress!

**Comment by rayriffy** [comment]
closed as stale
