### ISSUE TITLE
is `moduleResolution: "bundler"` really required?

### ISSUE THREAD

**Issue by nicholascostadev** [rayriffy/urami#6]
First, thank you for this library, it's really easy to get images optimized with no effort.

I tried using this library without it and it worked with no problem(I guess), I wonder what the implications are with not using `moduleResolution: "bundler"` that you said was required on the `README`.

edit1:

![image](https://github.com/rayriffy/svelte-aio/assets/86835927/c86f02ec-177c-4820-bcad-f1372775b8d3)

I actually have an error, but it's only types and works well.

**Comment by rayriffy** [comment]
It just a type-error that emitted out from TypeScript, no builds will break even you did not change this option. But if you do strict type-checking, this might be an option to enable. I might need to adjust some wording there.  🫣

**Comment by rayriffy** [comment]
resolved in [`1.0.2`](https://github.com/rayriffy/svelte-aio/releases/tag/v1.0.2)
